site_name: 2020_5CI_Team3
nav:
    - 'Project Charter': ''
    - 'Software Requirements Specification': ''
    - 'Software Project Management plan': ''
    - 'Business Model Canvas': ''
    - 'Project Model Canvas': ''
    
theme:
    name: readthedocs

use_directory_urls: true
